spring:
  profiles:
    active: dev
  # 数据库配置
  datasource:
    dynamic:
      datasource:
        master:
          url: jdbc:mysql://192.168.31.95:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
# 服务端口
server:
  port: 8888