spring:
  application:
    name: base
  web:
    resources:
      add-mappings: false
  profiles:
    active: dev
  # rabbitmq 配置
  rabbitmq:
    host: 192.168.31.95
    port: 5672
    username: admin
    password: admin
  # 数据库配置
  datasource:
    dynamic:
      datasource:
        master:
  # redis 配置
  redis:
    host: 192.168.31.95 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    timeout: 1000ms # 连接超时时间
# 服务端口
server:
  port: 8888

# 消息中间件类型 kafka rabbitmq
jms:
  type: kafka