spring:
  application:
    name: base
  web:
    resources:
      add-mappings: false
  profiles:
    active: dev
  # rabbitmq 配置
  rabbitmq:
    host: 192.168.1.36
    port: 5672
    username: admin
    password: admin
  # 数据库配置
  datasource:
    dynamic:
      datasource:
        master:
# 服务端口
server:
  port: 8888